# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_payment_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(684, 576)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(270, 490, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.newRecord_output = QtWidgets.QTableView(Dialog)
        self.newRecord_output.setGeometry(QtCore.QRect(40, 390, 571, 51))
        self.newRecord_output.setObjectName("newRecord_output")
        self.driverId_input = QtWidgets.QTextEdit(Dialog)
        self.driverId_input.setGeometry(QtCore.QRect(130, 100, 104, 31))
        self.driverId_input.setObjectName("driverId_input")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 110, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 170, 47, 13))
        self.label_2.setObjectName("label_2")
        self.amountPaid_input = QtWidgets.QTextEdit(Dialog)
        self.amountPaid_input.setGeometry(QtCore.QRect(130, 220, 104, 31))
        self.amountPaid_input.setObjectName("amountPaid_input")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 230, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(390, 170, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(360, 100, 71, 31))
        self.label_6.setObjectName("label_6")
        self.receivingBank_input = QtWidgets.QTextEdit(Dialog)
        self.receivingBank_input.setGeometry(QtCore.QRect(470, 220, 104, 31))
        self.receivingBank_input.setObjectName("receivingBank_input")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(360, 220, 71, 20))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 300, 91, 16))
        self.label_5.setObjectName("label_5")
        self.invoiceAmount_output = QtWidgets.QLabel(Dialog)
        self.invoiceAmount_output.setGeometry(QtCore.QRect(170, 300, 191, 16))
        self.invoiceAmount_output.setObjectName("invoiceAmount_output")
        self.inertion_output = QtWidgets.QLabel(Dialog)
        self.inertion_output.setGeometry(QtCore.QRect(50, 350, 101, 16))
        self.inertion_output.setObjectName("inertion_output")
        self.payementDate_input = QtWidgets.QDateEdit(Dialog)
        self.payementDate_input.setGeometry(QtCore.QRect(470, 100, 110, 22))
        self.payementDate_input.setObjectName("payementDate_input")
        self.paidFrom_input = QtWidgets.QDateEdit(Dialog)
        self.paidFrom_input.setGeometry(QtCore.QRect(130, 160, 110, 22))
        self.paidFrom_input.setObjectName("paidFrom_input")
        self.paidTo_input = QtWidgets.QDateEdit(Dialog)
        self.paidTo_input.setGeometry(QtCore.QRect(470, 160, 110, 22))
        self.paidTo_input.setObjectName("paidTo_input")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Driver_id"))
        self.label_2.setText(_translate("Dialog", "Paid_from"))
        self.label_3.setText(_translate("Dialog", "Amount"))
        self.label_4.setText(_translate("Dialog", "Paid_to"))
        self.label_6.setText(_translate("Dialog", "Payment_date"))
        self.label_7.setText(_translate("Dialog", "Receiving Bank"))
        self.label_5.setText(_translate("Dialog", "Invoice Amount:"))
        self.invoiceAmount_output.setText(_translate("Dialog", "Please tell me the payment period!"))
        self.inertion_output.setText(_translate("Dialog", "No changed made"))
