# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

software_version = '2.0'
company_name = 'HANSON MOTOR MANAGEMENT'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Login = QtWidgets.QFrame(self.centralwidget)
        self.Login.setGeometry(QtCore.QRect(110, 70, 621, 421))
        self.Login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Login.setObjectName("Login")
        self.Login_Button = QtWidgets.QPushButton(self.Login)
        self.Login_Button.setGeometry(QtCore.QRect(270, 260, 75, 23))
        self.Login_Button.setObjectName("Login_Button")
        self.Password_Input = QtWidgets.QPlainTextEdit(self.Login)
        self.Password_Input.setGeometry(QtCore.QRect(240, 210, 151, 31))
        self.Password_Input.setObjectName("Password_Input")
        self.userName_Input = QtWidgets.QPlainTextEdit(self.Login)
        self.userName_Input.setGeometry(QtCore.QRect(240, 160, 151, 31))
        self.userName_Input.setObjectName("userName_Input")
        self.userName = QtWidgets.QLabel(self.Login)
        self.userName.setGeometry(QtCore.QRect(160, 160, 61, 31))
        self.userName.setObjectName("userName")
        self.passWord = QtWidgets.QLabel(self.Login)
        self.passWord.setGeometry(QtCore.QRect(160, 220, 47, 13))
        self.passWord.setObjectName("passWord")
        self.Company_Name = QtWidgets.QLabel(self.Login)
        self.Company_Name.setGeometry(QtCore.QRect(20, 90, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Company_Name.setFont(font)
        self.Company_Name.setObjectName("Company_Name")
        self.Welcome = QtWidgets.QLabel(self.Login)
        self.Welcome.setGeometry(QtCore.QRect(20, 50, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Welcome.setFont(font)
        self.Welcome.setObjectName("Welcome")
        self.Login_Response = QtWidgets.QLabel(self.Login)
        self.Login_Response.setGeometry(QtCore.QRect(270, 300, 181, 31))
        self.Login_Response.setObjectName("Login_Response")
        self.System_Version = QtWidgets.QLabel(self.centralwidget)
        self.System_Version.setGeometry(QtCore.QRect(110, 20, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.System_Version.setFont(font)
        self.System_Version.setObjectName("System_Version")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # self.actionExit.trigger.connect(lambda: self.login_clicked("Bye!"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Login_Button.setText(_translate("MainWindow", "Login"))
        self.userName.setText(_translate("MainWindow", "Username"))
        self.passWord.setText(_translate("MainWindow", "Password"))
        self.Company_Name.setText(_translate("MainWindow", company_name))
        self.Welcome.setText(_translate("MainWindow", "Welcome!"))
        self.Login_Response.setText(_translate("MainWindow", "Please Login First!"))
        self.System_Version.setText(_translate("MainWindow", f"Taxi Management System V{software_version}"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

    def login_clicked(self, text):
        self.label.setText(text)
        self.label.adjustSzie()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
